"""add triggered_at to alerts

Revision ID: 45a343679b6f
Revises: eaf1a705802d
Create Date: 2026-07-06 19:46:24.091761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a343679b6f'
down_revision: Union[str, Sequence[str], None] = 'eaf1a705802d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'triggered_at')
    # ### end Alembic commands ###
